version: '3.5'
services:
  frontend:
      image: 'frontend-example'
      environment:
        - API_URL=http://localhost:8000
      ports: 
        - 5000:5000 
  backend:
      image: 'backend-example'
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - DB_NAME=postgres
        - DB_HOST=postgres
      ports:
        - 8000:8000
      depends_on: 
        - db
  redis:
      image: redis
      container_name: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
